//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadFacade.Surftown.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        public GAME()
        {
            this.TOURNAMENT = new HashSet<TOURNAMENT>();
        }
    
        public int ID { get; set; }
        public int GAME_TYPE_ID { get; set; }
        public int HOME_TEAM_ID { get; set; }
        public int AWAY_TEAM_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public int RESULT_ID { get; set; }
        public bool FINISHED { get; set; }
    
        public virtual GAME_TYPE GAME_TYPE { get; set; }
        public virtual RESULT RESULT { get; set; }
        public virtual TEAM TEAM { get; set; }
        public virtual TEAM TEAM1 { get; set; }
        public virtual ICollection<TOURNAMENT> TOURNAMENT { get; set; }
    }
}
