<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" Inherits="TestPages_DbConnection" Title="Untitled Page" Codebehind="DbConnection.aspx.cs" %>

<%--<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <script src="../JavaScript/editThickbox.js" type="text/javascript"></script>
</asp:Content>--%>
<%--<asp:Content ID="Content2" ContentPlaceHolderID="Header" Runat="Server">
</asp:Content>--%>

<asp:Content ID="Content3" ContentPlaceHolderID="Content" Runat="Server">
   
   <%--<asp:GridView ID="GridView2" DataSourceID="SqlDataSource1" runat="server" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" AutoGenerateDeleteButton="True" AllowSorting="True" EnableSortingAndPagingCallbacks="False" />--%>
   <asp:GridView ID="GridView1" runat="server" 
    AutoGenerateEditButton="True" 
    AutoGenerateSelectButton="True" 
    AutoGenerateDeleteButton="True" 
    AllowSorting="True" 
    EnableSortingAndPagingCallbacks="False" />


    <%--Master View--%>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ProviderName="System.Data.Odbc"
        DataSourceMode="DataSet"
        ConnectionString="<%$ ConnectionStrings:DataBase %>"
        SelectCommand="SELECT playerId, userId, alias FROM Players ORDER BY playerId"
        UpdateCommand="UPDATE Players SET
                        userId=?, alias=?
                        WHERE playerId=?"
        InsertCommand="INSERT INTO Players (userId, alias)
                        VALUES(?, ?)"
        DeleteCommand="DELETE FROM Players
                        WHERE playerId=?">
    </asp:SqlDataSource>

    <br /><br /><br />
    <asp:GridView ID="GridView2" runat="server" 
        EnableViewState="false"
        DataSourceID="SqlDataSource1"
        DataKeyNames="playerId"
        AllowSorting="true" 
        AutoGenerateDeleteButton="false" 
        AutoGenerateEditButton="false" 
        AutoGenerateSelectButton="true"
        OnRowCreated="GridView2_RowCreated"
        OnRowCommand="GridView2_RowCommand">
    </asp:GridView>
    
    
    <%--Detail View--%>
    <asp:SqlDataSource ID="RowDataSource" runat="server"
        ProviderName="System.Data.Odbc"
        DataSourceMode="DataSet"
        ConnectionString="<%$ ConnectionStrings:DataBase %>"
        SelectCommand="SELECT playerId, userId, alias FROM Players WHERE playerId=?"
        UpdateCommand="UPDATE Players SET
                        userId=?, alias=?
                        WHERE playerId=?"
        InsertCommand="INSERT INTO Players (userId, alias)
                        VALUES(?, ?)"
        DeleteCommand="DELETE FROM Players
                        WHERE playerId=?">
        <SelectParameters>
            <asp:ControlParameter Name="playerId" ControlID="GridView2" PropertyName="SelectedValue" />
        </SelectParameters>
    </asp:SqlDataSource>
    
    <%--<asp:HyperLink ID="hlAddNew" runat="server" NavigateUrl="~/TestPages/DbConnection.aspx?action=addnew">Lägg till ny</asp:HyperLink><br />--%>
    <asp:LinkButton Text="Lägg till ny" ID="lbAddNew" runat="server" OnClick="lbAddNew_Click">Lägg till ny</asp:LinkButton>
    <br />
    
    <asp:DetailsView ID="DetailsView1" DataSourceID="RowDataSource" runat="server" 
        DataKeyNames="playerId"
        Height="50px" Width="125px" 
        AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" 
        AutoGenerateInsertButton="True"
        AutoGenerateRows="false"
        OnItemUpdated="DetailsView1_ItemUpdated"
        OnItemInserted="DetailsView1_ItemInserted"
        OnItemDeleted="DetailsView1_ItemDeleted">
        <Fields>
            <%--<asp:BoundField DataField="playerId" HeaderText="playerId" ReadOnly="True" />--%>
            <asp:BoundField DataField="userId" HeaderText="userId" />
            <asp:BoundField DataField="alias" HeaderText="alias" />
        </Fields>
    </asp:DetailsView>
    
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="Footer" Runat="Server">
</asp:Content>
