//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galante.se.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHOR_TEST
    {
        public AUTHOR_TEST()
        {
            this.BOOK_TEST = new HashSet<BOOK_TEST>();
        }
    
        public int author_id { get; set; }
        public string author_name { get; set; }
    
        public virtual ICollection<BOOK_TEST> BOOK_TEST { get; set; }
    }
}
