//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galante.se.Models
{
    using galante.se.Models.Mappers;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurftownMsSqlEntities : DbContext
    {
        public SurftownMsSqlEntities()
            : base("name=SurftownMsSqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
            modelBuilder.Configurations.Add(new AuthorTestMap());
        }
    
        public DbSet<BOOK_TEST> BOOK_TEST { get; set; }
        public DbSet<AUTHOR_TEST> AUTHOR_TEST { get; set; }
    }
}
