//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class MasterPage {
    
    /// <summary>
    /// head control.
    /// </summary>
    /// <remarks>
    /// Auto-generated _currentTv.
    /// To modify move _currentTv declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
    
    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated _currentTv.
    /// To modify move _currentTv declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// Header control.
    /// </summary>
    /// <remarks>
    /// Auto-generated _currentTv.
    /// To modify move _currentTv declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ContentPlaceHolder Header;
    
    /// <summary>
    /// hlLogin control.
    /// </summary>
    /// <remarks>
    /// Auto-generated _currentTv.
    /// To modify move _currentTv declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HyperLink hlLogin;
    
    /// <summary>
    /// hlFootball control.
    /// </summary>
    /// <remarks>
    /// Auto-generated _currentTv.
    /// To modify move _currentTv declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HyperLink hlFootball;
    
    /// <summary>
    /// Content control.
    /// </summary>
    /// <remarks>
    /// Auto-generated _currentTv.
    /// To modify move _currentTv declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ContentPlaceHolder Content;
    
    /// <summary>
    /// Footer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated _currentTv.
    /// To modify move _currentTv declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ContentPlaceHolder Footer;
}
