//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadFacade.Surftown.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_TYPE
    {
        public GAME_TYPE()
        {
            this.GAME = new HashSet<GAME>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<GAME> GAME { get; set; }
    }
}
